version: '3'
services:
    web:
        build: apache
        image: pianos_web
        
        volumes:
            - ./apache/libs:/usr/share/php
            - ./apache/src:/var/www/html
            - ./apache/cdn:/var/www/html/cdn
        
        ports:
            - 127.0.0.1:80:80
    
    db:
        build: postgres
        image: pianos_db
        
        env_file:
            - .env
        
        volumes:
            - ./postgres/pgdata:/var/lib/postgresql/data/pgdata
        
        ports:
            - 127.0.0.1:5432:5432

